### ISSUE TITLE
Determine appropriate UTM projection for a geometry.

### ISSUE THREAD

**Issue by leehach** [gerrymandr/VRDI_DC#8]
Code exists currently in **utm_projections** branch to find correct UTM zone for spatial geometry. This code is currently a process run on a specific test geodataframe. The algorithm needs to be generalized and encapsulated in a function so that it can be called from other programs and applied to any geodataframe.

**Comment by eionblanc** [comment]
This was fixed and sent over to the MCMC team for use. I'm not sure how to update it here, or if that's worth pursuing. If DC team still needs this, let me know.
